# Generated by Django 5.1.5 on 2025-01-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_address_order_items_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='Not Processed'),
        ),
    ]
